In [ ]:
#Untitled6
# Linear Algebra
import numpy as np

# Data Processing
import pandas as pd

# Data visualization
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# Algorithm 

from sklearn.svm import SVC, LinearSVC

In [ ]:
#INPUT DATA
# Getting the data
from google.colab import files
uploaded = files.upload()

Saving UpdatedDataSet.csv to UpdatedDataSet.csv


In [ ]:
import io
kidney_data = pd.read_csv(io.BytesIO(uploaded['UpdatedDataSet.csv']))
print(kidney_data.head())

   Unnamed: 0  id  age    bp  ...  ane  classification        eGFR stages
0           0   0   48  80.0  ...   no             ckd   62.001841      2
1           1   1    7  50.0  ...   no             ckd  146.335929      1
2           2   2   62  80.0  ...  yes             ckd   36.866485      3
3           3   3   48  70.0  ...  yes             ckd   16.394927      4
4           4   4   51  80.0  ...   no             ckd   51.262906      3

[5 rows x 29 columns]


In [ ]:
kidney_data.columns

Index(['Unnamed: 0', 'id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc',
       'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn',
       'dm', 'cad', 'appet', 'pe', 'ane', 'classification', 'eGFR', 'stages'],
      dtype='object')

In [ ]:
kidney_data.drop(['id','classification','eGFR'],axis=1,inplace=True)

In [ ]:
kidney_data.columns

Index(['Unnamed: 0', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba',
       'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm',
       'cad', 'appet', 'pe', 'ane', 'stages'],
      dtype='object')

In [ ]:
# Understanding the Attributes

In [ ]:
'''Understanding the Attributes
age - age of patient
bp - blood pressure level of patient
sg - Specific gravity is the ratio of the density of the substance to the density of a reference substance.
al - Albumin ( It is a type of protein the liver makes. It's one of the most abundant proteins in the blood. We need a proper balance of albumin to keep fluid from leaking out of blood vessels.)
su - Sugar level in the blood
rbc - It refers to Red blood cells in the blood.
pc - Pus is the result of the body's natural immune system automatically responding to an infection, usually caused by bacteria or fungi.
pcc - Pyuria is a condition that occurs when excess white blood cells, or pus, are present in the urine.Parasites, kidney stones, tumors and cysts, and interstitial cystitis can also lead to pyuria.
ba - Bacteria
bgr - The reference values for a "normal" random glucose test in an average adult are 79–140mg/dl (4.4–7.8 mmol/l), between 140-200mg/dl (7.8–11.1 mmol/l) is considered pre-diabetes, and ≥ 200 mg/dl is considered diabetes according to ADA guidelines
bu - Nitrogen in the blood that comes from urea (a substance formed by the breakdown of protein in the liver). The kidneys filter urea out of the blood and into the urine. A high level of urea nitrogen in the blood may be a sign of a kidney problem.
sc - Serum Creatinine ( Creatinine is a breakdown product of creatinine phosphate in muscle, and is usually produced ata)
sod - Sodium (sod in mEq/L)
pot - Potassium (pot in mEq/L)
hemo - Hemoglobin (hemo in gms)
pcv - Packed Cell Volume
wc - White Blood Cell Count (wc in cells/cumm)
rc - Red Blood Cell Count(rc in millions/cumm)
htn - Hypertension (It is also known as high blood pressure(HBP) is a long-term medical condition in which the blood pressure in the arteries is persistently elevated.)
dm - Diabetes Mellitus(A disease in which the body’s ability to produce or respond to the hormone insulin is impaired, resulting in abnormal metabolism of carbohydrates and elevated levels of glucose in the blood.)
cad - Coronary Artery Disease (It happens when the arteries that supply blood to heart muscle become hardened and narrowed.)
appet - Appetite (A natural desire to satisfy a bodily need, especially for food)
pe - Pedal Edema( It is the accumulation of fluid in the feet and lower legs. )
ane - Anemia (A condition in which there is a deficiency of red cells or of haemoglobin in the blood, resulting in pallor and weariness.)
classification- It classifies whether a person is suffering from chronic kidney disease or not.

'''

'Understanding the Attributes\nage - age of patient\nbp - blood pressure level of patient\nsg - Specific gravity is the ratio of the density of the substance to the density of a reference substance.\nal - Albumin ( It is a type of protein the liver makes. It\'s one of the most abundant proteins in the blood. We need a proper balance of albumin to keep fluid from leaking out of blood vessels.)\nsu - Sugar level in the blood\nrbc - It refers to Red blood cells in the blood.\npc - Pus is the result of the body\'s natural immune system automatically responding to an infection, usually caused by bacteria or fungi.\npcc - Pyuria is a condition that occurs when excess white blood cells, or pus, are present in the urine.Parasites, kidney stones, tumors and cysts, and interstitial cystitis can also lead to pyuria.\nba - Bacteria\nbgr - The reference values for a "normal" random glucose test in an average adult are 79–140mg/dl (4.4–7.8 mmol/l), between 140-200mg/dl (7.8–11.1 mmol/l) is considere

In [ ]:
#Data Types of the data

kidney_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  400 non-null    int64  
 1   age         400 non-null    int64  
 2   bp          388 non-null    float64
 3   sg          353 non-null    float64
 4   al          354 non-null    float64
 5   su          351 non-null    float64
 6   rbc         248 non-null    object 
 7   pc          335 non-null    object 
 8   pcc         396 non-null    object 
 9   ba          396 non-null    object 
 10  bgr         356 non-null    float64
 11  bu          381 non-null    float64
 12  sc          400 non-null    float64
 13  sod         313 non-null    float64
 14  pot         312 non-null    float64
 15  hemo        348 non-null    float64
 16  pcv         330 non-null    object 
 17  wc          295 non-null    object 
 18  rc          270 non-null    object 
 19  htn         398 non-null    o

In [ ]:
# Categorical and Numerical Variables
# Categorical variable : rbc, pc, pcc, ba, pcv, wc, rc, htn, dm, cad, appet, pe, ane and classification
# Numerical variable : age, bp , sg, al, su, bgr, bu, sc, sod, pot and hemo.

In [ ]:
kidney_data.describe()

Unnamed: 0         age          bp  ...         pot        hemo      stages
count  400.000000  400.000000  388.000000  ...  312.000000  348.000000  400.000000
mean   199.500000   51.562500   76.469072  ...    4.627244   12.526437    2.777500
std    115.614301   16.982996   13.683637  ...    3.193904    2.912587    1.386651
min      0.000000    2.000000   50.000000  ...    2.500000    3.100000    1.000000
25%     99.750000   42.000000   70.000000  ...    3.800000   10.300000    2.000000
50%    199.500000   55.000000   80.000000  ...    4.400000   12.650000    3.000000
75%    299.250000   64.000000   80.000000  ...    4.900000   15.000000    4.000000
max    399.000000   90.000000  180.000000  ...   47.000000   17.800000    5.000000

[8 rows x 13 columns]

In [ ]:
# Count of null values
kidney_data.isnull().sum()

Unnamed: 0      0
age             0
bp             12
sg             47
al             46
su             49
rbc           152
pc             65
pcc             4
ba              4
bgr            44
bu             19
sc              0
sod            87
pot            88
hemo           52
pcv            70
wc            105
rc            130
htn             2
dm              2
cad             2
appet           1
pe              1
ane             1
stages          0
dtype: int64

In [ ]:
# Extracting null cols
null_cols = kidney_data.columns[kidney_data.isnull().any()]

In [ ]:
null_cols

Index(['bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sod',
       'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe',
       'ane'],
      dtype='object')

In [ ]:
# Replacing columns having null values using pad
for i in null_cols:
    kidney_data[i].fillna(method = 'pad',inplace = True)
    kidney_data[i].fillna(method = 'bfill',inplace = True)


In [ ]:
kidney_data.isna().sum().sum()

0

In [ ]:
kidney_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  400 non-null    int64  
 1   age         400 non-null    int64  
 2   bp          400 non-null    float64
 3   sg          400 non-null    float64
 4   al          400 non-null    float64
 5   su          400 non-null    float64
 6   rbc         400 non-null    object 
 7   pc          400 non-null    object 
 8   pcc         400 non-null    object 
 9   ba          400 non-null    object 
 10  bgr         400 non-null    float64
 11  bu          400 non-null    float64
 12  sc          400 non-null    float64
 13  sod         400 non-null    float64
 14  pot         400 non-null    float64
 15  hemo        400 non-null    float64
 16  pcv         400 non-null    object 
 17  wc          400 non-null    object 
 18  rc          400 non-null    object 
 19  htn         400 non-null    o

In [ ]:
categorical_columns = ['rbc','pc','pcc','ba','pcv','wc','rc','htn','dm','cad','appet','pe','ane']

In [ ]:
# Encoding Categorical Features

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for i in categorical_columns:
    kidney_data[i] = le.fit_transform(kidney_data[i])

In [ ]:
kidney_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  400 non-null    int64  
 1   age         400 non-null    int64  
 2   bp          400 non-null    float64
 3   sg          400 non-null    float64
 4   al          400 non-null    float64
 5   su          400 non-null    float64
 6   rbc         400 non-null    int64  
 7   pc          400 non-null    int64  
 8   pcc         400 non-null    int64  
 9   ba          400 non-null    int64  
 10  bgr         400 non-null    float64
 11  bu          400 non-null    float64
 12  sc          400 non-null    float64
 13  sod         400 non-null    float64
 14  pot         400 non-null    float64
 15  hemo        400 non-null    float64
 16  pcv         400 non-null    int64  
 17  wc          400 non-null    int64  
 18  rc          400 non-null    int64  
 19  htn         400 non-null    i

In [ ]:
#Normalizing features
kidney_data.columns

Index(['Unnamed: 0', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba',
       'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm',
       'cad', 'appet', 'pe', 'ane', 'stages'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler

normalizer = StandardScaler()
# for i in kidney_data.columns:
#     kidney_data[i] = pd.DataFrame(i:fit_transform(kidney_data[i]))
col = ['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane']

kidney_data[col] = normalizer.fit_transform(kidney_data[col].values)

In [ ]:
kidney_data.head()

Unnamed: 0       age        bp  ...        pe       ane  stages
0           0 -0.210031  0.278140  ... -0.484322 -0.420084       2
1           1 -2.627234 -1.903350  ... -0.484322 -0.420084       1
2           2  0.615355  0.278140  ... -0.484322  2.380476       3
3           3 -0.210031 -0.449023  ...  2.064742  2.380476       4
4           4 -0.033163  0.278140  ... -0.484322 -0.420084       3

[5 rows x 26 columns]

In [ ]:
#Model Building

kidney_data.columns

Index(['Unnamed: 0', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba',
       'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm',
       'cad', 'appet', 'pe', 'ane', 'stages'],
      dtype='object')

In [ ]:
x = kidney_data[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane']]
y = kidney_data['stages']

In [ ]:
print(len(x))
print(len(y))

400
400


In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [ ]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

320
80
320
80


In [ ]:
y.value_counts()

2    93
1    93
3    90
5    66
4    58
Name: stages, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
classifier = SVC(gamma = 0.01,C=100)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print("Accuracy score:",accuracy_score(y_test,y_pred))
print("Confusion Matrix :")
print(confusion_matrix(y_test,y_pred))

Accuracy score: 0.6625
Confusion Matrix :
[[ 8  6  1  0  0]
 [ 5 12  2  0  0]
 [ 2  2  8  1  0]
 [ 0  0  6 10  1]
 [ 0  1  0  0 15]]


In [ ]:
SVC()

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(y_pred)

[5 2 2 5 5 4 1 2 5 3 4 5 3 2 4 5 2 3 4 3 2 1 4 2 4 1 4 5 2 1 3 2 2 4 1 5 4
 2 3 2 1 1 5 1 2 4 3 2 3 3 2 3 3 3 1 2 2 3 3 5 5 2 3 1 5 1 5 3 5 2 2 1 3 5
 4 5 1 1 1 2]


In [ ]:
classifier = SVC(gamma = 0.01,C=100,kernel='linear')
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print("Accuracy score:",accuracy_score(y_test,y_pred))
print("Confusion Matrix :")
print(confusion_matrix(y_test,y_pred))

Accuracy score: 0.7875
Confusion Matrix :
[[13  2  0  0  0]
 [ 2 17  0  0  0]
 [ 0  3  9  0  1]
 [ 0  2  3 10  2]
 [ 0  0  1  1 14]]
